# Generated by Topia Endpoint Generator
# Endpoint: Dashboard
# Route: GET /dashboard

class DashboardEndpoint
  include Azu::Endpoint(Dashboardrequest, Dashboardresponse)

  get "/dashboard"

  def call : Dashboardresponse
    # TODO: Implement endpoint logic
    Dashboardresponse.new
  end
end
