# Generated by Topia Endpoint Generator
# Endpoint: Profile
# Route: GET /profile

class ProfileEndpoint
  include Azu::Endpoint(Getprofilerequest, Profileresponse)

  get "/profile"

  def call : Profileresponse
    # TODO: Implement endpoint logic
    Profileresponse.new
  end
end
