# Generated by Topia Endpoint Generator
# Endpoint: Settings
# Route: PUT /settings

class SettingsEndpoint
  include Azu::Endpoint(Updatesettingsrequest, Settingsresponse)

  put "/settings"

  def call : Settingsresponse
    # TODO: Implement endpoint logic
    Settingsresponse.new
  end
end
